04-quality-control.md
updated quality control lesson with example and took out pivot table
=> updated quality control lesson

01-format-data.md, index.md
I think there is a link to the wrong spreadsheet for the formatting data challenge. The text of the challenge matches up with this file referred to in the set up page.
=> Wrong spreadsheet for formatting data challenge?

00-intro.md
=> Fixed Typo in 00-intro.md

01-format-data.md
@tracykteal @cbahlai I'm submitting PRs to revise the learning objectives such that they align with Data Carpentry's assessment efforts.
=> Revised learning objectives

04-quality-control.md
@tracykteal merged the learning objectives that were revised, but the objective for this module was missing.
=> Added missing learning objective

06-data-formats-caveats.md
@tracykteal 
Learning objectives were revised and approved. There were two objectives missing on this page.
=> Added missing learning objectives

02-common-mistakes.md
Edited the table into a css table so that the display is better and the border functions as a solid line.
=> Table edited under Field name problems

index.md, instructor_notes.md
As I found the instructor notes a bit hard to read, I adapted the formatting and structuring a bit.
Content wise nothing has changed.
=> Fix instructor notes formatting

_episodes/01-format-data.md, _episodes/02-common-mistakes.md, _episodes/04-quality-control.md, _episodes/05-exporting-data.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/101
=> add key points remove duplicate LOs

_config.yml
=> add contact for DC

_episodes/01-format-data.md, _episodes/02-common-mistakes.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/100
=> minor wording changes

_episodes/03-dates-as-data.md, _episodes/04-quality-control.md, _episodes/05-exporting-data.md
Addresses most of https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/114
=> Minor wording

_episodes/00-intro.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/90
=> make lesson names consistent

_episodes/02-common-mistakes.md, _episodes/03-dates-as-data.md, _episodes/04-quality-control.md, _episodes/05-exporting-data.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/88
=> Bolding caps

_episodes/01-format-data.md, _episodes/02-common-mistakes.md, _episodes/03-dates-as-data.md, _episodes/04-quality-control.md, _episodes/05-exporting-data.md
This addresses the following issues:
- https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/108 (also partially addressed with https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/134)
- partially addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/123 about zipdisks
- https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/88
=> Shaming language

_episodes/00-intro.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/89
=> remove "accidentally"

_episodes/00-intro.md
Changed wording referencing LibreOffice as the primary spreadsheet program utilized during the lesson.
=> Update to Spreadsheet programs

_episodes/02-common-mistakes.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/105 and https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/107
=> Explain null

index.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/84
and a few minor wording changes
=> remove redundant language about data practices

_episodes/00-intro.md, _episodes/01-format-data.md, _episodes/02-common-mistakes.md, _episodes/03-dates-as-data.md, _episodes/04-quality-control.md, _episodes/05-exporting-data.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/77
=> Questions update

_episodes/02-common-mistakes.md
Fixes https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/81
=> add that 02-common-mistakes is a reference

_episodes/03-dates-as-data.md
factors are categorical variables
also remove "handy dandy" idiom
Fixes https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/115
=> explain factors

_episodes/03-dates-as-data.md, _episodes/04-quality-control.md
Fixes https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/120
=> Formatting exercises

_episodes/04-quality-control.md
Fixes https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/118
=> add guidelines and template for readme

_episodes/02-common-mistakes.md
Fixes https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/109
=> Make section headers consistent

_episodes/02-common-mistakes.md
Fixes https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/51
=> Add metadata enhancements

_episodes/05-exporting-data.md
Fixes https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/123
=> add point about non-stable open data formats

_episodes/01-format-data.md, assets/js/lesson.js
Added introduction to the dataset in 01-format-data before it's used in the exercise
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/75
=> added introduction to dataset

_episodes/01-format-data.md
=> updated language in 01-format-data

_episodes/01-format-data.md
Addresses part of https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/113
=> added solution for exercise in 01-format-data

setup.md
Added "(whichever is the most recent version)" to all download instructions in case anyone is confused by the X.X.X language.
Part of lesson release process.
=> clarify version

CONTRIBUTORS.md
There used to be several data sets in development for use with this lesson. All but one of these data sets have been removed, to focus on only a single consistent data set throughout the workshop. This PR removes references to the unused data sets.
Please delete the text below before submitting your contribution.
=> remove unused data refs

_extras/guide.md
Update instructor notes to use template format from lesson-example (https://raw.githubusercontent.com/swcarpentry/lesson-example/gh-pages/_extras/guide.md)
=> bring in template for instructor notes

CONDUCT.md, CONTRIBUTING.md, NEWS.md
=> added NEWS file for release and updated other admin files

_episodes/01-format-data.md
The sentence only needs the word treating once.
Please delete the text below before submitting your contribution. 
---
=> The word treating is duplicated here

_episodes/02-common-mistakes.md
In response to issue #198
Best quick solution at the time as DOI at journal not resolving
=> Fixed link to nine simple rules

setup.md
As suggested in https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/207
=> Added full data citation as suggested in issue 207

_episodes/00-intro.md
@tracykteal @cbahlai Updated the learning objective in the first episode of this lesson so that it's consistent with the rest of the "actionable" learning objectives.
=> Updated learning objective

CITATION
One of the participants in my NEON/QUBES FMN is citing this lesson and still had the FIXME text in the citation. This appears to be the correct DOI. Feel free to reject PR if not.
=> Add Zenodo DOI.

_episodes/02-common-mistakes.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/45. Adding information about why there might be null values, and some suggestions for addressing those different reasons.
=> added reasons for confusing null values

_episodes/00-intro.md, _episodes/03-dates-as-data.md
Discussed in spreadsheet ecology issue 'Revised Learning Objectives for "Data Organization in Spreadsheets" #197'
=> Updated learning outcomes

_episodes/04-quality-control.md
This pull request solves issue #256.
=> Updated Step1 on the last exercise for Conditional formatting

_episodes/05-exporting-data.md
This pull request solves issue #251 
This is a contribution to instruction check out
Regards
Kemi Megbowon
=> Replaced 'xls' with 'xlsx' to solve issue #251

_episodes/02-common-mistakes.md
Fixed small typo in the URL so it displays as a link.
=> Small typo in URL

_episodes/04-quality-control.md
Just fixing two typos in episode 04
=> Fixing two typos

_extras/datamanagement.md
Added YAML header to datamanagement.md
=> added YAML header

CODE_OF_CONDUCT.md
Updating link to CoC link text to 'The Carpentries'
=> updating CoC link text

CITATION, README.md
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/272
=> updating citation information from release

_episodes/05-exporting-data.md
As in [L18](https://github.com/katrinleinweber/spreadsheet-ecology-lesson/blob/44486255f60283ef07637c23881b0304cf190d49/_episodes/05-exporting-data.md#L18) ;-)
=> Fix formatting

_episodes/01-format-data.md
Currently, the latter term is suddenly used as a refence in the end.
=> Connect "structuring data" list to "tidy data"

_episodes/00-intro.md, _episodes/01-format-data.md, _episodes/02-common-mistakes.md, _episodes/03-dates-as-data.md, _episodes/04-quality-control.md, _episodes/05-exporting-data.md
Thanks @cbahlai @apawlik for your incredible work leading the original version of this lesson! With your permission, removing the section at the top listing authors, to provide consistency with other lessons, and moving our author and editor/maintainer credit over to Zenodo through lesson publications.
Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/280
=> updated episodes removing the list of authors there

_extras/guide.md
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck …
=> Minor typo fix

_episodes/04-quality-control.md
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.
=> Lesson Contribution: Update 04-quality-control.md

_episodes/02-common-mistakes.md
the formatting problems episode incorrectly referenced itself as a lesson.
=> correct "lesson" to "episode"

_episodes/01-format-data.md
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
instructor.training@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at …
=> Missing 'are' on line 160

_episodes/02-common-mistakes.md
This works on my desktop for converting the Null data table to HTML.
=> null data HTML conversion

_episodes/01-format-data.md
update "Data Organization in Spreadsheets" citation to peer-reviewed version: https://www.tandfonline.com/doi/full/10.1080/00031305.2017.137598
=> update citation to peer-reviewed version

_includes/check_transition_variables.html, _includes/lesson_footer.html, _includes/life_cycle.html, _includes/navbar.html, _layouts/base.html, assets/css/lesson.scss, bin/boilerplate/_config.yml
Bringing the lesson template up-to-date in preparation for the planned infrastructure transition.
=> Update to final version of styles lesson template

setup.md
I'm having trouble parsing the setup because the parser thinks that the prereq tag belongs to the inner block quote. I'm adding an extra line to make it behave.
Please merge this before 03 May
=> fix setup for workbench transition

episodes/02-common-mistakes.md
Closes Issue #340
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate …
=> Update 02-common-mistakes.md - Issue #340

episodes/04-quality-control.md
Inserted interstitial step to find validation in excel now, from workshop experience today.
=> MS added a layer between data and validation
